export const languages = [
    {code: "en", name: "English"},
    {code: "es", name: "Spanish"},
    {code: "fr", name: "French"},
    {code: "de", name: "German"},
    {code: "zh", name: "Chinese"},
    {code: "hi", name: "Hindi"},
    {code: "ar", name: "Arabic"},
    {code: "pt", name: "Portuguese"},
    {code: "ja", name: "Japanese"},
    {code: "ko", name: "Korean"},
    {code: "ru", name: "Russian"},
    {code: "it", name: "Italian"},
    {code: "tr", name: "Turkish"},
    {code: "nl", name: "Dutch"},
    {code: "sv", name: "Swedish"},
    {code: "fi", name: "Finnish"},
    {code: "da", name: "Danish"},
    {code: "no", name: "Norwegian"},
    {code: "pl", name: "Polish"},
    {code: "cs", name: "Czech"},
    {code: "hu", name: "Hungarian"},
    {code: "id", name: "Indonesian"},
    {code: "th", name: "Thai"},
];

export const religions = [
    { code: "non_religious", name: "Non-religious" },
    { code: "african_traditional", name: "African Traditional & Diasporic" },
    { code: "agnostic", name: "Agnostic" },
    { code: "atheist", name: "Atheist" },
    { code: "bahai", name: "Baha'i" },
    { code: "buddhism", name: "Buddhism" },
    { code: "cao_dai", name: "Cao Dai" },
    { code: "chinese_traditional", name: "Chinese Traditional Religion" },
    { code: "christianity", name: "Christianity" },
    { code: "hinduism", name: "Hinduism" },
    { code: "islam", name: "Islam" },
    { code: "jainism", name: "Jainism" },
    { code: "juche", name: "Juche" },
    { code: "judaism", name: "Judaism" },
    { code: "neo_paganism", name: "Neo-Paganism" },
    { code: "rastafarianism", name: "Rastafarianism" },
    { code: "secular", name: "Secular" },
    { code: "shinto", name: "Shinto" },
    { code: "sikhism", name: "Sikhism" },
    { code: "spiritism", name: "Spiritism" },
    { code: "tenrikyo", name: "Tenrikyo" },
    { code: "unitarian_universalism", name: "Unitarian-Universalism" },
    { code: "zoroastrianism", name: "Zoroastrianism" },
    { code: "primal_indigenous", name: "Primal-Indigenous" },
    { code: "other", name: "Other" }
];
