export const languages = [
    {code: "en", name: "English"},
    {code: "es", name: "Spanish"},
    {code: "fr", name: "French"},
    {code: "de", name: "German"},
    {code: "zh", name: "Chinese"},
    {code: "hi", name: "Hindi"},
    {code: "ar", name: "Arabic"},
    {code: "pt", name: "Portuguese"},
    {code: "ja", name: "Japanese"},
    {code: "ko", name: "Korean"},
    {code: "ru", name: "Russian"},
    {code: "it", name: "Italian"},
    {code: "tr", name: "Turkish"},
    {code: "nl", name: "Dutch"},
    {code: "sv", name: "Swedish"},
    {code: "fi", name: "Finnish"},
    {code: "da", name: "Danish"},
    {code: "no", name: "Norwegian"},
    {code: "pl", name: "Polish"},
    {code: "cs", name: "Czech"},
    {code: "hu", name: "Hungarian"},
    {code: "id", name: "Indonesian"},
    {code: "th", name: "Thai"},
];